### PR TITLE
Resolved the issue #3

### PR DESCRIPTION
**Pull request by deepanshu-sharmaa**

### CODE REVIEW

**Comment by deepanshu-sharmaa** [comment]
Hey @anshss @IshaanTyagi, I have resolved the issue #3 by adding a small piece of code.
Please merge this PR and add the hacktober-accepted tags.

**Comment by Prerna-0202** [comment]
@ar-ray0111, Please review

**Comment by ar-ray0111** [comment]
good job @deepanshu-sharmaa 
@Prerna-0202 please merge the branch

**Comment by deepanshu-sharmaa** [comment]
A big thanks to @Prerna-0202  and @ar-ray0111

**Pull request merged**
